language: python

services:
  - docker

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy:v1
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:v1
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1
  - docker tag udagram-frontend:local $DOCKER_USERNAME/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/reverseproxy:v1
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:v2
